```mermaid
classDiagram
    class Team {
        -String name
        -List~Player~ players
        +Team(String name)
        +addPlayer(Player player) void
        +removePlayer(int id) void
    }

    class Player {
        -String name
        -int age
        +Player(String name, int age)
        +modifyName(String name) void
        +getAge() int
    }

    Team  -->  Player
